"""create admin table

Revision ID: 76c52a77ace8
Revises: cfb7ad0f5ee3
Create Date: 2026-07-22 08:35:26.847141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76c52a77ace8'
down_revision: Union[str, Sequence[str], None] = 'cfb7ad0f5ee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.alter_column('players', 'overall',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players', 'potential',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players', 'value',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players', 'salary',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'salary',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('players', 'value',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('players', 'potential',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('players', 'overall',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
